version: "3.8"

services:
  homespital-randomizer-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homespital-randomizer
    ports:
      - "60002:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./data:/app/data
    restart: unless-stopped
